language:
  - node_js

node_js:
  - stable
  - 6
  - 4

cache:
  directories:
    - $HOME/.npm
    - node_modules

install:
  - npm update
  - npm prune

deploy:
  on:
    branch: master
    node: stable
  provider: npm
  email: hello@smartcar.com
  api_key: $NPM_API_TOKEN
