language:
  - node_js

node_js:
  - '10'
  - '8'
  - '6'

cache:
  directories:
    - $HOME/.npm

if: tag IS blank # do not build tags

before_install:
  - dpkg --compare-versions `npm -v` ge 6.0 || npm i -g npm@latest

install:
  - npm ci

script:
  - npm test

deploy:
  provider: npm
  email: hello@smartcar.com
  api_key: $NPM_TOKEN
  on:
    branch: master
    node: '10'
